# Site settings
title: Hacker Analytics
email: zack@hackeranalytics.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog about penetration testing and security assessments.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
github_username: yourusername

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

# Permalinks
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true 