backend:
  name: git-gateway
  branch: main  # Change this if your default branch is different

site_url: https://hackeranalytics.com
display_url: https://hackeranalytics.com
logo_url: https://hackeranalytics.com/logo.png

media_folder: "static/images/uploads" # Adjust to your repo structure
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
